[project]
name = "TBCards"
version = "0.0.1"
authors = [
  { name="Aspen A.M. Meissner", email="aikorrana@gmail.com" },
]
description = "A free and open-source python library that provides tools for creating text-based card games."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0"
license-files = ["LICENSE"]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
    "sphinx-rtd-theme",
    "flake8",
    "python-semantic-release"
]

[project.urls]
Homepage = "https://github.com/epsilonemae/TBCards"
Issues = "https://github.com/epsilonemae/TBCards/issues"
